[package]
name = "titanrt-binance"
version = "0.1.0"
edition = "2024"

[dependencies]
titanrt = {version = "0.1.3", features = ["connector"]}
anyhow = "1.0.99"
serde = { version = "1.0.219", features = ["derive"] }